### ISSUE TITLE
swift build error on the config-updates branch

### ISSUE THREAD

**Issue by rvennam** [IBM-Cloud/get-started-swift#5]
$ swift build
error: The dependency graph could not be satisfied because an update to `https://github.com/IBM-Swift/Swift-cfenv.git' is required

**Comment by rolivieri** [comment]
@rvennam You need to remove your Packages folder (`rm -rf Packages`) and rebuild again (`swift build`). You are running into a limitation in SwiftPM.

**Comment by rvennam** [comment]
Ah - I was going to do that but I was hoping there was a better way.
